author: qfast.io
title: QFast
description: Quality Comes First
description2: Independent software architect and consultant specializing in various technologies.
contact_page: https://twitter.com/qfast-io
sitemap: /sitemap.xml

# language to use in html tag, can be overriden by page.lang
# lang: en

# You can look up the color names at http://materializecss.com/color.html
colors:
    primary_dark: black
    primary_light: grey-darken-1
    primary: grey-darken-3
    accent: light-blue
    accent_dark_1: light-blue-darken-1
    accent_dark_2: light-blue-darken-2
    primary_text: grey-darken-4
    secondary_text: grey-darken-1
    inverse_text: white
    divider: grey-lighten-1
    secondaryBackground: grey-lighten-4

# path to logo without leading slash e.g. images/logo.png or just the file name if it is in the root directory
logo: assets/images/logo.png
#banner path
banner_arch_1: assets/images/banner-arch-1.jpg
banner_arch_2: assets/images/banner-arch-2.jpg
banner_arch_3: assets/images/banner-arch-3.jpg
banner_team_1: assets/images/banner-team-1.jpg
banner_team_2: assets/images/banner-team-2.jpg
banner_team_3: assets/images/banner-team-3.jpg

# Github data, if present there will be a GitHub button in the navbar
github_button:
  user: qfast-io
  project: repositories

# Twitter data, if present there will be a Twitter button in the navbar
youtube_button:
  user: qfast-io

# Linked data, if present there will be a Linked button in the navbar
linkedin_button:
  user: qfast-io

collections:
  landingpage:
    output: true
  portfolio:
    output: true
    navbar_title: Portfolio
    order: 10
  # products:
  #   output: true
  #   news_relevant: true
  #   news_icon: apps
  #   navbar_title: Products
  #   order: 20
  videos:
    output: true
    navbar_title: Videos
    news_relevant: true
    news_icon: course
    order: 30
  blogs:
    output: true
    news_relevant: true
    news_icon: blog
    navbar_title: Blogs
    order: 40
  # chat:
  #   output: true
  #   navbar_title: Chat
  #   order: 50
  about:
    output: true
    navbar_title: About
    order: 60
