author: qfast.io
title: QFast
description: Quality Comes First
contact_page: https://twitter.com/qfast-io

# language to use in html tag, can be overriden by page.lang
# lang: en

# You can look up the color names at http://materializecss.com/color.html
colors:
    primary_dark: black
    primary_light: grey-darken-1
    primary: grey-darken-3
    accent: light-blue
    primary_text: grey-darken-4
    secondary_text: grey-darken-1
    inverse_text: white
    divider: grey-lighten-1
    secondaryBackground: grey-lighten-4

# path to logo without leading slash e.g. images/logo.png or just the file name if it is in the root directory
logo: assets/images/logo.png
#banner path
banner_arch_1: assets/images/banner-arch-1.jpg
banner_arch_2: assets/images/banner-arch-2.jpg
banner_arch_3: assets/images/banner-arch-3.jpg
banner_team_1: assets/images/banner-team-1.jpg
banner_team_2: assets/images/banner-team-2.jpg
banner_team_3: assets/images/banner-team-3.jpg

# Github data, if present there will be a GitHub button in the navbar
github_button:
  user: qfast-io
  project: repositories

# Twitter data, if present there will be a Twitter button in the navbar
twitter_button:
  user: qfast-io

# Linked data, if present there will be a Linked button in the navbar
linkedin_button:
  user: qfast-io

collections:
  landingpage:
    output: true
  projects:
    output: true
    navbar_title: Projects
    order: 10
  products:
    output: true
    news_relevant: true
    news_icon: apps
    navbar_title: Products
    order: 20
  courses:
    output: true
    navbar_title: Courses
    news_relevant: true
    news_icon: course
    order: 30
  blogs:
    output: true
    news_relevant: true
    news_icon: blog
    navbar_title: Blogs
    order: 40
  chat:
    output: true
    navbar_title: Chat
    order: 50
  about:
    output: true
    navbar_title: About
    order: 60
